os: linux
language: node_js
node_js:
  "stable"
sudo: required
services:
    - docker 
env:
 global:
   - USERNAME = manshaehsan
   - PASS=loyelopassword! 
bofore_install:
   - docker login -u $USERNAME -p $PASS
   - docker build -t manshaehsan/knight:tCI .
   - docker ps 
   - docker push manshaehsan/knight:tCI
    
