os: linux
language: node_js
node_js:
  "stable"
sudo: required
services:
    - docker 
bofore_install:
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker build -t manshaehsan/knight:tCI .
   - docker ps 
   - docker push manshaehsan/knight:tCI
    
