os: linux
sudo: required
services:
    - docker 
bofore_install:
   - docker login -u "manshaehsan" -p "loyelopassword!"
   - docker build -t manshaehsan/knight:tCI .
   - docker ps 
   - docker push manshaehsan/knight:tCI
    
